### ISSUE TITLE
Send email to cluster operators and/or groups

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/gitops-automation-script#5]
We should send mails to cluster operators and/or the deploying group when a GitHub action is triggered.

I recommend using Mailgun: https://documentation.mailgun.com/en/latest/api-intro.html

We would need to additionally store a Mailgun token in the repository and update documentation appropriately.

You ought to be able to get the cluster operator's mail by looking at the cluster info, and then getting the administrating group of the cluster, and then getting the email address from that. Scooping up the deploying group's email should be the same approach.

I don't know how easily parsable the response will be if you shell out to the CLI, so it might make more sense to make direct requests to the SLATE API and parse out the appropriate objects. (aside: someone please make a Python API for SLATE :) )

**Comment by cnweaver** [comment]
It's four lines of code in python, not counting imports or error handling:

    cluster_response = requests.get(api_endpoint+"/clusters/"+cluster_name_or_id, params={"token": token})
    group_name = cluster_response.json()["metadata"]["owningGroup"]
    group_response = requests.get(api_endpoint+"/groups/"+group_name, params={"token": token})
    group_email = group_response.json()["metadata"]["email"]

**Comment by sthapa** [comment]
Should be resolved with the mailgun script that I merged.
